version: '3.9'
services:
  server:
    build:
      context: ./
      dockerfile: Dockerfile
    env_file:
      - ./env/.env.production
    tty: true
    stdin_open: true
    ports:
      - 5003:5003
