version: '3.9'
services:
  server:
    build:
      context: ./
      dockerfile: Dockerfile
      args:
        DOCKER_ENV: 'stage'
    env_file:
      - ../../.env
    tty: true
    stdin_open: true
    ports:
      - 5004:5004
