name: Velog Deployment workflow

on:
  push:
    branches: 'release'
    paths:
      - 'packages/velog-server/**'
      - 'packages/velog-web/**'
env:
  AWS_REGION: ap-northeast-2
  ECR_WEB_REPOSITORY: velog-web
  ECR_SERVER_REPOSITORY: velog-server

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install pnpm
        uses: pnpm/action-setup@v2
        with:
          version: latest

      - name: Setup Node.js
        uses: actions/setup-node@v3.7.0
        with:
          node-version: 18.16

      - name: Install Dependencies
        run: pnpm install

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Install Dependencies
        run: pnpm parameter pull -e ${{ secrets.ENVIRONMENT }}
        working-directory: ./infrastructure
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

      - name: pulumi actions
        uses: pulumi/actions@v4.4.0
        with:
          command: up
          stack-name: /${{ secrets.ENVIRONMENT }} # or org-name/stack-name
          diff: true
          upsert: true
          work-dir: './infrastructure'
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          PULUMI_ACCESS_TOKEN: ${{ secrets.PULUMI_ACCESS_TOKEN }}
