name: Velog Server test workflow

on:
  push:
    branches: ['main', 'development', 'hotfix']
    paths:
      - 'packages/velog-server/**'
  pull_request:
    branches: ['main', 'development', 'hotfix']
    paths:
      - 'packages/velog-server/**'

jobs:
  test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: './packages/velog-server'

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3.7.0
        with:
          node-version: 18.16

      - name: Install pnpm
        uses: pnpm/action-setup@v2
        with:
          version: latest

      - name: Install Dependencies
        run: pnpm install

      - name: Primsa generate
        run: pnpm prisma generate

      - name: Build
        run: pnpm build

      - name: Run Tests
        run: pnpm test
