name: Velog Server test workflow

on:
  push:
    branches: ['main', 'development', 'hotfix']
    paths:
      - 'packages/velog-server/**'
      - '.github/workflows/velog-server-test.yml'
  pull_request:
    branches: ['main', 'development', 'hotfix']
    paths:
      - 'packages/velog-server/**'
      - '.github/workflows/velog-server-test.yml'
env:
  PNPM_CACHE_FOLDER: .pnpm-store

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.16]
    defaults:
      run:
        working-directory: './packages/velog-server'

    steps:
      - uses: actions/checkout@v3
      - uses: pnpm/action-setup@v2
        with:
          version: 8.6.12
      - name: Setup Node.js v${{ matrix.node-version }}
        uses: actions/setup-node@v3.7.0
        with:
          node-version: ${{ matrix.node-version }}

      - run: pnpm prisma:copy && npx prisma generate
      - run: pnpm install

      - run: pnpm ssm pull -e test
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

      - run: pnpm test
